name: Deploy ClickCat App

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      AWS_REGION: eu-north-1
      FRONT_IMAGE_NAME: clickcat-frontend
      BACK_IMAGE_NAME: clickcat-backend

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Configure AWS credentials via secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Run tests
      - name: Run unit tests
        run: |
          cd backend
          npm install
          npm test

      # 5. Define image URIs
      - name: Set image names
        run: |
          echo "FRONT_IMAGE=662195598891.dkr.ecr.eu-north-1.amazonaws.com/${{ env.FRONT_IMAGE_NAME }}:latest" >> $GITHUB_ENV
          echo "BACK_IMAGE=662195598891.dkr.ecr.eu-north-1.amazonaws.com/${{ env.BACK_IMAGE_NAME }}:latest" >> $GITHUB_ENV

      # 6. Build and push frontend image
      - name: Build frontend image
        run: |
          docker build -f step3.Dockerfile -t $FRONT_IMAGE .
          docker push $FRONT_IMAGE

      # 7. Build and push backend image
      - name: Build backend image
        run: |
          docker build -f backend/Dockerfile -t $BACK_IMAGE ./backend
          docker push $BACK_IMAGE
